name: Testes Automatizados com Behave e Selenium

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Google Chrome e ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '114.0.5735.90'  # Substitua pela versão desejada
          install-dependencies: true
          install-chromedriver: true

      - name: Executar testes
        run: behave
